apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - backend:
          serviceName: nginx-svc 
          servicePort: 80
