apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
status:
  loadBalancer:
    ingress:
      - ip: 10.4.20.110
      - ip: 10.4.20.128
      - ip: 10.4.20.129
